mode: rule
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  default-nameserver:
  - 114.114.114.114
  - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
ipv6: true
mixed-port: 7890
log-level: info
allow-lan: false
proxy-groups:
- name: DIRECT
  type: select
  proxies:
  - DIRECT
- name: 节点选择
  type: select
  proxies: []
- name: Google
  type: select
  proxies: []
- name: Netflix
  type: select
  proxies: []
- name: Telegram
  type: select
  proxies: []
rules:
- GEOIP,CN,DIRECT
- MATCH,节点选择
